spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: mailcheinvia@provamail.com
    password: LaTuaPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect